spring.application.name=backend
spring.datasource.url=jdbc:h2:mem:localfolddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=8080
cesga.api.url=https://api-mock-cesga.onrender.com
gemini.api.key=${GEMINI_API_KEY:API_KEY_AQUI_PON_LA_TUYA}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
